### ISSUE TITLE
Fix Readme.md when running npm run dev

### ISSUE THREAD

**Issue by rekjuh** [oskariorg/oskari-documentation-site#22]
When starting dev server (npm run dev), Node.js gives the following error:

'next' is not recognized as an internal or external command,
operable program or batch file.

To solve the error, run **npm install react react-dom next** to install next before running npm run dev.

**Comment by ZakarFin** [comment]
True, it doesn't say anything about installing the dependencies. I think the readme is mostly unedited one from the `create-next-app` command. But you should do `npm install` before running (no need to specify what needs to be installed as everything is covered in the package.json). We should probably add that to the readme :)

**Comment by ZakarFin** [comment]
Edited the readme to say this.
