### ISSUE TITLE
Add new menu item: Getting Started

### ISSUE THREAD

**Issue by rekjuh** [oskariorg/oskari-documentation-site#53]
Add new menu item: Getting Started.
Under menu one new page (with HTML anchor to different places on the same page):

For owners & procurers
For developers
For admins
For commercial partners
For end-users

Let's start with one page for all and separate them to different pages if needed.

**Comment by rekjuh** [comment]
WIP
![image](https://github.com/oskariorg/oskari-documentation-site/assets/87303508/66ef72d3-05cd-4081-b750-2da34adb8ab3)

**Comment by ZakarFin** [comment]
I thought we agreed on this being under "Discover" as just one new option "Getting started"?

**Comment by ZakarFin** [comment]
#57 added the Getting started with a placeholder page under "Discover Oskari": https://github.com/oskariorg/oskari-documentation-site/blob/e9181934ea28ccef8964cc813dac2ca6446ff19e/app/discover/gettingstarted/page.tsx

**Comment by ZakarFin** [comment]
I guess we can keep this open as a reminder we need to have some content on the page.
